name: Python Tests with Pytest

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: List files in runner (before setup)
        run: |
          echo "Contenido del runner ANTES de instalar dependencias:"
          ls -R

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: List files in runner (after setup)
        run: |
          echo "Contenido del runner DESPUÉS de instalar dependencias:"
          ls -R

      - name: Run tests
        run: |
          export PYTHONPATH="${PYTHONPATH}:${GITHUB_WORKSPACE}"
          pytest tests/ -v
